### PR TITLE
Corrected image background for contrast changes

### PR DESCRIPTION
**Pull request by Ayush23Dash**

### CODE REVIEW

**Comment by sachin10101998** [comment]
@Ayush23Dash please provide a description of whatever changes you propose to make in a file when you send a PR or you could link the issue which you are trying to solve through this. If you were trying to fix @28 and @29, then the file changes that you made in this PR have been already proposed by me in #35

**Comment by Ayush23Dash** [comment]
Yes i saw it before but on implementing it there was a UI mismatch on the anchor tag.

**Comment by sachin10101998** [comment]
@Ayush23Dash I am still not sure what exactly you are talking about. Could you link the issue which you are solving through this PR or provide a description of the enhancement feature or UI/UX change you are proposing?

**Comment by Ayush23Dash** [comment]
Amm i will be linking to the further description of this PR in the #51 PR. I will be adding the screenshots of the problem in some time.
Thanks

**Comment by sachin10101998** [comment]
I guess these changes which you have proposed are trying to solve #28 and #29. This same change, however, has already been proposed in #35 which hasn't been merged yet. This PR is a duplicate of #35. You can close this PR and add the description of changes you propose in #51 which seems to solve a different issue.

**Pull request closed without merging**
