### PR TITLE
FLUID-6324: fix Docpad version issues.

### PR DESCRIPTION
**Pull request by jobara**
Also does the following:
- pins dependency versions
- removes package-lock.json
- adds npm scripts for docpad build and deploy
- updates README

https://issues.fluidproject.org/browse/FLUID-6324

### CODE REVIEW

**Comment by jobara** [comment]
@jhung could you please review this

**Comment by sachin10101998** [comment]
@jobara , I tried this fix on Ubuntu 18.04 with Node 13.9.0 and Docpad 6.82.5. 
Docpad freezes while building the site. I am attaching the build report. Can you please look at it once to see for possible errors.
Here's the [Link](https://drive.google.com/file/d/1ev81dBdgDy-c6il6WR96JHzLuRxeIOX6/view?usp=sharing) for report.

**Comment by jobara** [comment]
@sachin10101998 with this PR is should be using the locally installed version of Docpad at version 6.79.4 and not a globally installed version. From your output file it looks like that's the case.

Thanks for reporting that docpad run halts. I've fixed the `npm run docpad` script.

**Comment by sachin10101998** [comment]
Thanks. The build was successful and the site is working perfectly on my local server.

**Comment by jobara** [comment]
@jhung if this PR is acceptable, it would be helpful to merge for other PRs that are coming in.

**Pull request merged**
