### PR TITLE
FLUID-5590: fixed style and script links in non root folder

### PR DESCRIPTION
**Pull request by sachin10101998**
fixes FLUID-5590

### CODE REVIEW

**Comment by jobara** [comment]
@sachin10101998 thanks for looking into this. So I'm thinking that instead of duplicating the scripts and styles documents that we turn them back into eco files. Then in the partials we can take in a second parameter to pass in the base of the URL for the news pages. see: https://github.com/docpad/docpad-plugin-partials

Scripts template
```
<script src="<% @baseURL>lib/infusion/infusion-all.js"></script>
<script src="<% @baseURL>js/uio.js"></script>
```

In the post layout:
```
        <%- @partial('scripts', {baseURL: "..\"}) %>
        <%- @partial('styles', {baseURL: "..\"}) %>
```

There might be some refinement needed tot he above for performance, to avoid having to specify it on the baseURL on the default layouts, and etc. But this would avoid duplication.

**Comment by jobara** [comment]
And we should also make sure that this still works https://github.com/fluid-project/fluidproject.org/blob/master/src/files/js/uio.js

**Comment by sachin10101998** [comment]
@jobara, updated the PR using the partials plugin. It's working perfectly and without duplication of scripts. Great fix.

**Comment by sachin10101998** [comment]
@jobara, updated the PR using the partials plugin. It's working perfectly and without duplication of scripts. Great fix.

**Comment by jobara** [comment]
merged at 96771c3fddecad7ec1cca0375757f527f1e5ad64

**Pull request merged**
