### PR TITLE
NOJIRA: Add analytics tracking code

### LINKED ISSUE #57: Add analytics tracking code
Add this code to the <head></head> section:

```
<!-- Matomo -->
<script type="text/javascript">
  var _paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="https://analytics.inclusivedesign.ca/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '7']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Matomo Code -->
```

### PR DESCRIPTION
**Pull request by gtirloni**
resolves #57

### CODE REVIEW

**Comment by gtirloni** [comment]
> @gtirloni this looks good, although I don't know how to verify that the metrics are actually being collected. Also, I think we should like to the [Privacy Policy](https://wiki.fluidproject.org/display/fluid/Privacy+Policy). I think we can add it to the footer somewhere. Maybe @jhung has some thoughts on that. This is all interim anyways as the site is going to be redesigned.

You can look in dev tools / network if it's trying to contact analytics.inclusivedesign.ca (matomo.js).

Once it does, the statistics will be available [here](https://analytics.inclusivedesign.ca/index.php?module=CoreHome&action=index&idSite=7&period=day&date=yesterday&updated=1#?idSite=7&period=day&date=yesterday&category=Dashboard_Dashboard&subcategory=1)

**Comment by gtirloni** [comment]
@jobara Now that are Privacy Policy mentioned Matomo (thanks for that!), does this look good for merging?

**Comment by jobara** [comment]
@gtirloni I think ideally we'd add a link to the Privacy Policy on the site. However, this site is going to be redone so maybe it's okay for now. I've filed #59 for that work.

**Comment by jobara** [comment]
merged at 74ef95e50f3528f7558512120885550b03974769

**Pull request merged**
