### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by AsaoluElijah**
Modified build instructions to make installation process easier.

### CODE REVIEW

**Comment by AbdullahiAbdulkabir** [comment]
Brilliant idea @AsaoluElijah

**Comment by AsaoluElijah** [comment]
Thanks @AbdullahiAbdulkabir I hoped this got merged soon

**Review by Raunaksingh100 — CHANGES_REQUESTED** [review]
No need of this because this  website is migrated to static site generator and the readme file is already updates,,
see this readme file which is updated by our mentors here the link --
https://github.com/fluid-project/fluidproject.org/blob/master/README.md

**Comment by greatislander** [comment]
Thanks for this, but the project no longer uses docpad.

**Pull request closed without merging**
